import { analyzeReadiness } from "@/lib/readinessEngine";
import {
  AnalyzeCaseRequest,
  DocumentItem,
  EvidenceItem,
  PriorAuthCase,
  ServiceLine,
} from "@/lib/types";

function dateFromNow(days: number, hour = 10) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
}

function dateOnlyFromNow(days: number) {
  return dateFromNow(days).slice(0, 10);
}

function serviceLine(
  overrides: Partial<ServiceLine> & Pick<ServiceLine, "id" | "cpt" | "description">
): ServiceLine {
  return {
    covered: "Unknown",
    coveragePercent: "",
    authorizationRequirement: "Unknown",
    referralRequirement: "Unknown",
    networkRequirement: "In-network provider",
    requestedUnits: 1,
    visitLimit: null,
    usedUnits: null,
    remainingUnits: null,
    copay: "",
    coinsurance: "",
    deductibleApplies: "Unknown",
    source: "Not verified",
    verifiedDate: "",
    referenceNumber: "",
    reviewState: "Not reviewed",
    ...overrides,
  };
}

function documentItem(
  overrides: Partial<DocumentItem> & Pick<DocumentItem, "id" | "name">
): DocumentItem {
  return {
    required: "Unknown",
    status: "Needs review",
    blocking: false,
    source: "Not verified",
    fileName: "",
    verifiedDate: "",
    notes: "",
    ...overrides,
  };
}

function evidenceItem(
  overrides: Partial<EvidenceItem> & Pick<EvidenceItem, "id" | "title" | "type">
): EvidenceItem {
  return {
    source: "Not verified",
    capturedAt: "",
    applicableDate: "",
    referenceNumber: "",
    fileName: "",
    notes: "",
    humanConfirmed: false,
    ...overrides,
  };
}

const common = {
  dateOfBirth: "1997-04-18",
  providerName: "Dr. Taylor Reed",
  facilityName: "Sample Outpatient Center",
  placeOfService: "11 - Office",
  telehealth: false,
  owner: "Human Reviewer" as const,
  followUpDueAt: dateFromNow(1),
  createdAt: new Date().toISOString(),
  humanReviewRequired: true,
  humanConfirmed: false,
};

const ptRequest: AnalyzeCaseRequest = {
  ...common,
  id: "demo-pt-001",
  caseIdentifier: "PAIQ-PT-001",
  patientLabel: "Sample Patient: Jordan Miller",
  practiceName: "Lakeside Physical Therapy",
  appointmentAt: dateFromNow(1, 9),
  dateOfService: dateOnlyFromNow(1),
  specialty: "Physical Therapy",
  insurance: {
    payer: "Northstar Health Plan",
    planName: "Northstar Choice PPO",
    memberId: "FAKE-NS-10482",
    groupNumber: "FAKE-GRP-77",
    planType: "PPO",
    primaryInsurance: "Northstar Health Plan",
    secondaryInsurance: "Example Secondary Plan",
    eligibilityStatus: "Active",
    effectiveDate: dateOnlyFromNow(-180),
    terminationDate: "",
    networkStatus: "Unknown",
    cobStatus: "COB information missing",
    cobLastVerifiedDate: "",
    behavioralHealthAdministrator: "Not applicable",
    patientResponsibility: {
      copay: "$35",
      deductible: "$1,500",
      deductibleMet: "$450",
      coinsurance: "20%",
      outOfPocketMax: "$6,000",
      outOfPocketMet: "$1,100",
      expectedPatientAmount: "Not calculated",
      status: "Manual confirmation required",
    },
    source: "Manually entered",
    sourceDate: dateOnlyFromNow(-2),
    referenceNumber: "",
    verifiedBy: "Sample scheduler",
  },
  services: [
    serviceLine({
      id: "pt-cpt-97161",
      cpt: "97161",
      description: "PT evaluation, low complexity",
      covered: "Yes",
      coveragePercent: "80% after deductible",
      authorizationRequirement: "Not required",
      referralRequirement: "Required",
      requestedUnits: 1,
      visitLimit: 30,
      usedUnits: 0,
      remainingUnits: 30,
      copay: "$35",
      coinsurance: "20%",
      deductibleApplies: "Yes",
      source: "Verified from payer",
      verifiedDate: dateOnlyFromNow(-2),
      referenceNumber: "NS-PORTAL-77102",
      reviewState: "Verified",
    }),
    serviceLine({
      id: "pt-cpt-97110",
      cpt: "97110",
      description: "Therapeutic exercises",
      covered: "Unknown",
      authorizationRequirement: "Unknown",
      referralRequirement: "Required",
      requestedUnits: 8,
      visitLimit: 30,
      usedUnits: 0,
      remainingUnits: 30,
      source: "Not verified",
      reviewState: "Query",
    }),
  ],
  diagnoses: [
    {
      id: "pt-dx-1",
      icd10: "M25.561",
      description: "Pain in right knee",
      position: "Primary",
      linkedCpts: ["97161", "97110"],
      supportingNote:
        "Provider note mentions knee pain after sports activity but lacks objective measures and measurable functional goals.",
      supportStatus: "Missing support",
      source: "Verified from EHR",
      humanReviewed: false,
    },
  ],
  authorization: {
    status: "Unclear",
    authorizationNumber: "",
    submittedDate: "",
    effectiveDate: "",
    expirationDate: "",
    approvedCpts: [],
    approvedUnits: null,
    usedUnits: null,
    supportingDocumentationAttached: "Unknown",
    letterPresent: false,
    source: "Not verified",
    referenceNumber: "",
    notes: "Evaluation may not require authorization; follow-up CPT requirements were not checked.",
  },
  referral: {
    status: "Missing",
    referralNumber: "",
    referringProvider: "Dr. Sample Primary Care",
    effectiveDate: "",
    expirationDate: "",
    approvedCpts: [],
    documentPresent: false,
    source: "Manually entered",
    notes: "Referral is mentioned in scheduling notes but no document is attached.",
  },
  documents: [
    documentItem({
      id: "pt-doc-card",
      name: "Insurance card",
      required: "Required",
      status: "Present",
      blocking: true,
      source: "Uploaded payer document",
      fileName: "fake-insurance-card.pdf",
      verifiedDate: dateOnlyFromNow(-2),
    }),
    documentItem({
      id: "pt-doc-referral",
      name: "Referral",
      required: "Required",
      status: "Missing",
      blocking: true,
      source: "Not verified",
    }),
    documentItem({
      id: "pt-doc-poc",
      name: "Plan of care",
      required: "Required",
      status: "Missing",
      blocking: true,
      source: "Not verified",
    }),
    documentItem({
      id: "pt-doc-note",
      name: "Provider clinical note",
      required: "Required",
      status: "Needs review",
      blocking: false,
      source: "Verified from EHR",
      fileName: "fake-pt-evaluation-note.pdf",
      notes: "Objective measures and functional goals need review.",
    }),
    documentItem({
      id: "pt-doc-eligibility",
      name: "Eligibility verification PDF",
      required: "Required",
      status: "Missing",
      blocking: false,
      source: "Not verified",
    }),
  ],
  evidence: [
    evidenceItem({
      id: "pt-evidence-note",
      title: "Sample provider note",
      type: "Provider note",
      source: "Verified from EHR",
      capturedAt: dateFromNow(-2),
      applicableDate: dateOnlyFromNow(1),
      fileName: "fake-pt-evaluation-note.pdf",
      humanConfirmed: true,
    }),
  ],
  reviewerNotes:
    "Focus the review on COB, CPT 97110 coverage, authorization requirements, referral, plan of care, and clinical support.",
  sourceCaseText:
    "FAKE / SAMPLE CASE ONLY. Patient is scheduled for a PT evaluation and eight follow-up visits. Eligibility was briefly checked, but COB, network status, CPT 97110 benefits, authorization, referral documentation, and plan of care remain unresolved.",
  demoAcknowledged: true,
};

const behavioralRequest: AnalyzeCaseRequest = {
  ...common,
  id: "demo-bh-001",
  caseIdentifier: "PAIQ-BH-001",
  patientLabel: "Sample Patient: Avery Thompson",
  practiceName: "Clearview Behavioral Health",
  appointmentAt: dateFromNow(2, 14),
  dateOfService: dateOnlyFromNow(2),
  specialty: "Behavioral Health",
  providerName: "Morgan Lee, PMHNP",
  facilityName: "Clearview Behavioral Health",
  placeOfService: "10 - Telehealth in patient home",
  telehealth: true,
  insurance: {
    payer: "ExampleCare Medical",
    planName: "ExampleCare Silver HMO",
    memberId: "FAKE-EC-90811",
    groupNumber: "FAKE-BH-11",
    planType: "HMO",
    primaryInsurance: "ExampleCare Medical",
    secondaryInsurance: "",
    eligibilityStatus: "Active",
    effectiveDate: dateOnlyFromNow(-90),
    terminationDate: "",
    networkStatus: "In network",
    cobStatus: "No secondary coverage reported",
    cobLastVerifiedDate: dateOnlyFromNow(-1),
    behavioralHealthAdministrator: "CarePath Behavioral Services",
    patientResponsibility: {
      copay: "$25",
      deductible: "$500",
      deductibleMet: "$500",
      coinsurance: "0%",
      outOfPocketMax: "$3,500",
      outOfPocketMet: "$900",
      expectedPatientAmount: "$25 copay; final amount not guaranteed",
      status: "Verified",
    },
    source: "Verified from payer",
    sourceDate: dateOnlyFromNow(-1),
    referenceNumber: "CP-BH-42019",
    verifiedBy: "Sample eligibility specialist",
  },
  services: [
    serviceLine({
      id: "bh-cpt-90791",
      cpt: "90791",
      description: "Psychiatric diagnostic evaluation",
      covered: "Yes",
      coveragePercent: "100% after copay",
      authorizationRequirement: "Not required",
      referralRequirement: "Not required",
      requestedUnits: 1,
      visitLimit: null,
      usedUnits: 0,
      remainingUnits: null,
      copay: "$25",
      coinsurance: "0%",
      deductibleApplies: "No",
      source: "Verified from payer",
      verifiedDate: dateOnlyFromNow(-1),
      referenceNumber: "CP-BH-42019",
      reviewState: "Verified",
    }),
    serviceLine({
      id: "bh-cpt-90837",
      cpt: "90837",
      description: "Psychotherapy, 60 minutes",
      covered: "Yes",
      coveragePercent: "100% after copay",
      authorizationRequirement: "Required",
      referralRequirement: "Not required",
      requestedUnits: 12,
      visitLimit: 20,
      usedUnits: 8,
      remainingUnits: 12,
      copay: "$25",
      coinsurance: "0%",
      deductibleApplies: "No",
      source: "Verified from payer",
      verifiedDate: dateOnlyFromNow(-1),
      referenceNumber: "CP-BH-42019",
      reviewState: "Query",
    }),
  ],
  diagnoses: [
    {
      id: "bh-dx-1",
      icd10: "F41.1",
      description: "Generalized anxiety disorder",
      position: "Primary",
      linkedCpts: ["90791", "90837"],
      supportingNote: "Fictional intake assessment is present.",
      supportStatus: "Supported",
      source: "Verified from EHR",
      humanReviewed: true,
    },
  ],
  authorization: {
    status: "Pending",
    authorizationNumber: "FAKE-PENDING-1882",
    submittedDate: dateOnlyFromNow(-1),
    effectiveDate: "",
    expirationDate: "",
    approvedCpts: [],
    approvedUnits: null,
    usedUnits: null,
    supportingDocumentationAttached: "Yes",
    letterPresent: false,
    source: "Verified from payer",
    referenceNumber: "AUTH-TRACE-1882",
    notes: "Authorization request is pending for recurring 90837 visits.",
  },
  referral: {
    status: "Not required",
    referralNumber: "",
    referringProvider: "",
    effectiveDate: "",
    expirationDate: "",
    approvedCpts: [],
    documentPresent: false,
    source: "Verified from payer",
    notes: "No referral required per fake payer response.",
  },
  documents: [
    documentItem({
      id: "bh-doc-card",
      name: "Insurance card",
      required: "Required",
      status: "Present",
      blocking: true,
      source: "Uploaded payer document",
      fileName: "fake-bh-insurance-card.pdf",
      verifiedDate: dateOnlyFromNow(-1),
    }),
    documentItem({
      id: "bh-doc-intake",
      name: "Behavioral health intake assessment",
      required: "Required",
      status: "Present",
      blocking: true,
      source: "Verified from EHR",
      fileName: "fake-intake-assessment.pdf",
      verifiedDate: dateOnlyFromNow(-1),
    }),
    documentItem({
      id: "bh-doc-auth",
      name: "Authorization letter",
      required: "Required",
      status: "Missing",
      blocking: false,
      source: "Not verified",
      notes: "Pending payer decision.",
    }),
  ],
  evidence: [
    evidenceItem({
      id: "bh-evidence-eligibility",
      title: "Behavioral health payer portal response",
      type: "Payer portal",
      source: "Verified from payer",
      capturedAt: dateFromNow(-1),
      applicableDate: dateOnlyFromNow(2),
      referenceNumber: "CP-BH-42019",
      fileName: "fake-bh-eligibility.pdf",
      humanConfirmed: true,
    }),
  ],
  reviewerNotes:
    "Verify the pending 90837 authorization before recurring sessions. Keep the case visible until a payer response and letter are recorded.",
  sourceCaseText:
    "FAKE / SAMPLE CASE ONLY. Behavioral-health coverage and carve-out administrator are confirmed. Initial intake is ready, but recurring therapy requires authorization and the request is still pending.",
  demoAcknowledged: true,
};

const painRequest: AnalyzeCaseRequest = {
  ...common,
  id: "demo-pain-001",
  caseIdentifier: "PAIQ-PM-001",
  patientLabel: "Sample Patient: Riley Carter",
  practiceName: "Harbor Pain Specialists",
  appointmentAt: dateFromNow(5, 11),
  dateOfService: dateOnlyFromNow(5),
  specialty: "Pain Management",
  providerName: "Dr. Cameron Wells",
  facilityName: "Harbor Pain Specialists",
  insurance: {
    payer: "Summit Benefit Plan",
    planName: "Summit Gold PPO",
    memberId: "FAKE-SM-77601",
    groupNumber: "FAKE-PM-08",
    planType: "PPO",
    primaryInsurance: "Summit Benefit Plan",
    secondaryInsurance: "",
    eligibilityStatus: "Active",
    effectiveDate: dateOnlyFromNow(-240),
    terminationDate: "",
    networkStatus: "In network",
    cobStatus: "No secondary coverage reported",
    cobLastVerifiedDate: dateOnlyFromNow(0),
    behavioralHealthAdministrator: "Not applicable",
    patientResponsibility: {
      copay: "$50",
      deductible: "$1,000",
      deductibleMet: "$1,000",
      coinsurance: "10%",
      outOfPocketMax: "$4,500",
      outOfPocketMet: "$2,200",
      expectedPatientAmount: "Estimated from payer response; human review required",
      status: "Verified",
    },
    source: "Verified from payer",
    sourceDate: dateOnlyFromNow(0),
    referenceNumber: "SUMMIT-REF-550021",
    verifiedBy: "Sample benefits reviewer",
  },
  services: [
    serviceLine({
      id: "pain-cpt-64483",
      cpt: "64483",
      description: "Injection, anesthetic and/or steroid, transforaminal epidural",
      covered: "Yes",
      coveragePercent: "90% after deductible",
      authorizationRequirement: "Required",
      referralRequirement: "Not required",
      requestedUnits: 1,
      visitLimit: 3,
      usedUnits: 0,
      remainingUnits: 3,
      copay: "$50",
      coinsurance: "10%",
      deductibleApplies: "Yes",
      source: "Verified from payer",
      verifiedDate: dateOnlyFromNow(0),
      referenceNumber: "SUMMIT-CPT-64483-9",
      reviewState: "Verified",
    }),
  ],
  diagnoses: [
    {
      id: "pain-dx-1",
      icd10: "M54.16",
      description: "Radiculopathy, lumbar region",
      position: "Primary",
      linkedCpts: ["64483"],
      supportingNote: "Fictional clinical note and imaging summary are present.",
      supportStatus: "Supported",
      source: "Verified from EHR",
      humanReviewed: true,
    },
  ],
  authorization: {
    status: "Approved",
    authorizationNumber: "FAKE-AUTH-64022",
    submittedDate: dateOnlyFromNow(-5),
    effectiveDate: dateOnlyFromNow(-1),
    expirationDate: dateOnlyFromNow(30),
    approvedCpts: ["64483"],
    approvedUnits: 1,
    usedUnits: 0,
    supportingDocumentationAttached: "Yes",
    letterPresent: true,
    source: "Uploaded payer document",
    referenceNumber: "SUMMIT-AUTH-64022",
    notes: "Approved for one unit during the recorded date range.",
  },
  referral: {
    status: "Not required",
    referralNumber: "",
    referringProvider: "",
    effectiveDate: "",
    expirationDate: "",
    approvedCpts: [],
    documentPresent: false,
    source: "Verified from payer",
    notes: "No referral required under the fictional PPO plan.",
  },
  documents: [
    documentItem({
      id: "pain-doc-card",
      name: "Insurance card",
      required: "Required",
      status: "Present",
      blocking: true,
      source: "Uploaded payer document",
      fileName: "fake-pain-insurance-card.pdf",
      verifiedDate: dateOnlyFromNow(0),
    }),
    documentItem({
      id: "pain-doc-note",
      name: "Provider clinical note",
      required: "Required",
      status: "Present",
      blocking: true,
      source: "Verified from EHR",
      fileName: "fake-pain-provider-note.pdf",
      verifiedDate: dateOnlyFromNow(-1),
    }),
    documentItem({
      id: "pain-doc-imaging",
      name: "Imaging report",
      required: "Required",
      status: "Present",
      blocking: true,
      source: "Verified from EHR",
      fileName: "fake-lumbar-imaging.pdf",
      verifiedDate: dateOnlyFromNow(-10),
    }),
    documentItem({
      id: "pain-doc-auth",
      name: "Authorization letter",
      required: "Required",
      status: "Present",
      blocking: true,
      source: "Uploaded payer document",
      fileName: "fake-authorization-letter.pdf",
      verifiedDate: dateOnlyFromNow(0),
    }),
  ],
  evidence: [
    evidenceItem({
      id: "pain-evidence-eligibility",
      title: "CPT-specific benefits verification",
      type: "Eligibility PDF",
      source: "Verified from payer",
      capturedAt: dateFromNow(0),
      applicableDate: dateOnlyFromNow(5),
      referenceNumber: "SUMMIT-REF-550021",
      fileName: "fake-summit-benefits.pdf",
      humanConfirmed: true,
    }),
    evidenceItem({
      id: "pain-evidence-auth",
      title: "Authorization approval letter",
      type: "Authorization letter",
      source: "Uploaded payer document",
      capturedAt: dateFromNow(0),
      applicableDate: dateOnlyFromNow(5),
      referenceNumber: "SUMMIT-AUTH-64022",
      fileName: "fake-authorization-letter.pdf",
      humanConfirmed: true,
    }),
  ],
  reviewerNotes:
    "All core checks are complete. Final human confirmation should verify the authorization letter dates, approved CPT, and one-unit limit.",
  sourceCaseText:
    "FAKE / SAMPLE CASE ONLY. Eligibility, CPT-specific benefits, network, diagnosis support, authorization, and required documents are recorded with payer evidence. Human confirmation remains required.",
  demoAcknowledged: true,
};

export const sampleCaseRequests: AnalyzeCaseRequest[] = [
  ptRequest,
  behavioralRequest,
  painRequest,
];

export const demoCases: PriorAuthCase[] = sampleCaseRequests.map((item) =>
  analyzeReadiness(item)
);

export const defaultSampleCase = demoCases[0];
